# Use the official Python base image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the rest of the application code to the container
COPY . .

# Install the Python dependencies
RUN pip install -e .

EXPOSE 5000
# Set the command to run the application
CMD ["python", "main.py"]
