import "./globals.scss";
import { Inter } from "next/font/google";
import React, { ReactNode, useState } from "react";
import BurgerMenu from "./components/burger-menu/burger-menu";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Schwerpunktfeuerwehr Wolfenbüttel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html>
      <body>
        <BurgerMenu/>
      </body>
    </html>
  );
}
