import './globals.css'
import { Inter } from 'next/font/google'
import React, { ReactNode } from 'react';
import Image from 'next/image';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="shape-container">
            <div className="shape">
                <div className="logo_nav">
                    <Image
                      src="/logo.png"
                      width={75}
                      height={72}
                      alt='Logo'
                      priority={true}
                    />
                    <nav className="menu">
                        <ul>
                          <li><a href="#">Home</a></li>
                          <li><a href="#">Über uns</a></li>
                          <li><a href="#">Feuerwache</a></li>
                          <li><a href="#">Fahrzeuge</a></li>
                          <li><a href="#">Kontakt</a></li>
                        </ul>
                        <button className="join-button">Mitglied werden</button>
                    </nav>
                </div>
                <div className="text-container-landing">
                    <span>Für dich im</span><br />
                    <span className="sub-text-landing">Einsatz</span>
                </div>
            </div>
        </div>
        {children}
      </body>

      <footer>
        <div className="name-and-social-media">
          <div className="text-container-footer">
            <span>Schwerpunktfeuerwehr</span><br />
            <span className="sub-text-footer">Wolfenbüttel</span>
          </div>
          <div className="social-media-icon">
            <img className="not-last-image" src="" alt="instagram" />
            <img className="not-last-image" src="" alt="youtube" />
            <img src="" alt="facebook" />
          </div>
        </div>
        <div className="email-and-policy">
          <div className="email">
            <img src="" alt="email" />
            <span>info@Schwerpunktfeuerwehrwf.de</span>
          </div>
          <div className="privacy-policy">
            <span className="first-span">Privacy policy</span>
            <span>Terms & Condition</span>
          </div>
        </div>
      </footer>

    </html>
  )
}